import React, { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext();

// ─── Full Translation Dictionary ─────────────────────────────────────────────
const translations = {
  hi: {
    // ── Navbar ──
    'nav.home':        'होम',
    'nav.about':       'परिचय',
    'nav.poems':       'कविताएँ',
    'nav.books':       'पुस्तकें',
    'nav.quotes':      'उद्धरण',
    'nav.submitPoem':   'कविता भेजें',
    'nav.contact':     'संपर्क',
    'nav.invitePoets': 'कवयित्रियों को आमंत्रित करें',
    'nav.poets':       'कंचन लता जायसवाल एवं गरिमा सिंह',
    'lang.toggle':     'EN',
    'lang.current':    'हिंदी',

    // ── Hero ──
    'hero.badge':        'अक्षर कैनवास • कविता, कला एवं आत्मा का धाम',
    'hero.title1':       'जहाँ विचार रंग बनते हैं,',
    'hero.title2':       'और शब्द साहित्य में ढलते हैं।',
    'hero.subtitle':     'कवयित्री कंचन लता जायसवाल एवं गरिमा सिंह',
    'hero.lead':         'भावनात्मक गहराई, समकालीन रोमांस और दार्शनिक अंतर्दृष्टि से बुनी एक साहित्यिक कृति। यहाँ दो पीढ़ियों की काव्य प्रतिभा का स्वर्णिम संगम है।',
    'hero.explorePoems': 'कविता संग्रह देखें',
    'hero.discoverBooks':'प्रकाशित पुस्तकें देखें',
    'hero.badge1.role':  'दर्शन एवं विरासत',
    'hero.badge2.role':  'आधुनिक ग़ज़लें एवं युवा स्वर',
    'hero.art.pill':     'अक्षर कैनवास • शब्द • कला • आत्मा',
    'hero.art.quote':    '"कागज़ के कैनवास पर जब स्याही की बूँदें गिरती हैं, तो मौन भी एक अमर राग बन जाता है।"',

    // ── Featured Poems ──
    'featuredPoems.subtitle': 'काव्य-धारा',
    'featuredPoems.title1':   'चर्चित',
    'featuredPoems.title2':   'कविताएँ एवं ग़ज़लें',
    'featuredPoems.desc':     'अस्तित्वगत सत्य, कोमल प्रेम और सांस्कृतिक अनुगूँज को समेटे चुनिंदा रचनाएँ।',
    'featuredPoems.readBtn':  'पूरी कविता पढ़ें',
    'featuredPoems.viewAll':  'पूरा कविता संग्रह देखें',
    'featuredPoems.by':       'द्वारा',

    // ── Poets Spotlight ──
    'spotlight.subtitle':    'साहित्य के स्तंभ',
    'spotlight.title1':      'कवयित्री',
    'spotlight.title2':      'परिचय',
    'spotlight.desc':        'दो पीढ़ियों का अद्भुत समन्वय — शाश्वत सांस्कृतिक गहराई और सजीव आधुनिक संवेदनशीलता का अनूठा संगम।',
    'spotlight.books':       'पुस्तकें',
    'spotlight.service':     'साहित्य सेवा',
    'spotlight.journey':     'सृजन यात्रा',
    'spotlight.readBio':     'पूरी जीवनी पढ़ें',

    // ── Books Showcase ──
    'books.subtitle':        'साहित्यिक विरासत',
    'books.title1':          'प्रकाशित एवं',
    'books.title2':          'आगामी पुस्तकें',
    'books.desc':            'दोनों कवयित्रियों के अमर विचारों और छंदों को संजोए पुस्तकें एवं प्रतीक्षित संकलन।',
    'books.viewDetails':     'विवरण एवं अंश देखें',
    'books.viewAll':         'सभी पुस्तकें एवं ऑर्डर विकल्प देखें',
    'books.upcoming':        '✨ आगामी प्रकाशन',
    'books.published':       'प्रकाशित',

    // ── Quotes Carousel ──
    'quotes.subtitle':       'साहित्यिक प्रेरणाएँ एवं विचार',
    'quotes.title1':         'महान लेखकों के',
    'quotes.title2':         'प्रिय उद्धरण',
    'quotes.desc':           'जब कंचन लता जी और गरिमा जी अन्य महान लेखकों की रचनाएँ पढ़ती हैं और कोई पंक्ति उनके मन को छू जाती है, तो वे उसे अपने विचारों सहित यहाँ सहेज लेती हैं।',
    'quotes.viewAll':        'सभी उद्धरण एवं प्रेरणाएँ देखें',
    'quotes.source':         'स्रोत:',
    'quotes.curatedBy':      '💡 संकलन:',
    'quotes.likes':          'पसंद',
    'quotes.viewCard':       'कार्ड देखें एवं साझा करें',

    // ── Royal CTA ──
    'cta.tag':           'साहित्यिक उत्सव एवं काव्य-पाठ आमंत्रण',
    'cta.heading1':      'अपने समारोह को सजाएँ',
    'cta.heading2':      'अमर छंदों और भावनाओं से',
    'cta.sub':           'कवयित्री कंचन लता जायसवाल और गरिमा सिंह को राष्ट्रीय कवि सम्मेलनों, मुशायरों, विश्वविद्यालय संगोष्ठियों, साहित्य उत्सवों और पुस्तक वाचन कार्यक्रमों के लिए आमंत्रित करें।',
    'cta.invite':        'साहित्यिक आमंत्रण भेजें',
    'cta.write':         'कवयित्रियों को पत्र लिखें',

    // ── Footer ──
    'footer.brand.desc':     'प्रसिद्ध कवयित्रियों कंचन लता जायसवाल और गरिमा सिंह का आधिकारिक साहित्यिक मंच। एक कालातीत यात्रा जहाँ शब्द, भावनाएँ और सांस्कृतिक अनुगूँज एक साथ बुनी जाती हैं।',
    'footer.nav.heading':    'नेविगेशन',
    'footer.nav.home':       'होम',
    'footer.nav.about':      'कवयित्रियों का परिचय',
    'footer.nav.poems':      'कविता संग्रह',
    'footer.nav.books':      'प्रकाशित पुस्तकें',
    'footer.nav.quotes':     'प्रेरणाएँ एवं उद्धरण',
    'footer.themes.heading': 'थीम एवं रचनाएँ',
    'footer.theme.1':        'जीवन दर्शन एवं रहस्यवाद',
    'footer.theme.2':        'समकालीन प्रेम एवं ग़ज़लें',
    'footer.theme.3':        'स्त्री स्वर एवं सशक्तिकरण',
    'footer.theme.4':        'आगामी महासंकलन',
    'footer.theme.5':        'काव्य आयोजन आमंत्रण',
    'footer.newsletter.heading': 'काव्य गज़ट',
    'footer.newsletter.desc':    'विशेष छंद, पांडुलिपि के अंश और कार्यक्रम सूचनाएँ सीधे अपने इनबॉक्स में पाएँ।',
    'footer.newsletter.placeholder': 'अपना ईमेल पता दर्ज करें...',
    'footer.newsletter.btn':  'सदस्यता लें',
    'footer.newsletter.success': '✨ धन्यवाद! आपकी सदस्यता सफलतापूर्वक दर्ज हो गई।',
    'footer.rights':          'सर्वाधिकार सुरक्षित।',
    'footer.authors':         'रचयिताएँ:',

    // ── About ──
    'about.subtitle':        'साहित्यिक तीर्थयात्रा',
    'about.title1':          'जीवनी एवं',
    'about.title2':          'काव्य-दर्शन',
    'about.desc':            'दो साहित्यिक पीढ़ियों का गहन संगम — जहाँ शास्त्रीय गहराई समकालीन अनुगूँज से मिलती है।',
    'about.stat.volumes':    'प्रकाशित संग्रह:',
    'about.stat.verses':     'रचित छंद:',
    'about.stat.dedication': 'साहित्य समर्पण:',
    'about.stat.ghazals':    'रचित ग़ज़लें:',
    'about.stat.journey':    'सक्रिय यात्रा:',
    'about.honors':          'प्रमुख सम्मान एवं पुरस्कार',
    'about.timeline.subtitle': 'समय के पदचिह्न',
    'about.timeline.title1': 'मील के पत्थर एवं',
    'about.timeline.title2': 'प्रमुख उपलब्धियाँ',
    'about.timeline.desc':   'कविता की साधना को आकार देने वाले निर्णायक क्षण।',
    'about.milestone.1.title': 'एक साहित्यिक अभियान का आरंभ',
    'about.milestone.1.desc':  'कंचन लता जायसवाल की आरंभिक शास्त्रीय रचनाओं को प्रमुख राष्ट्रीय साहित्यिक पत्रिकाओं में व्यापक मान्यता मिली।',
    'about.milestone.2.title': 'गरिमा सिंह का काव्य-उदय',
    'about.milestone.2.desc':  'युवा कवयित्री गरिमा सिंह ने प्रतिष्ठित विश्वविद्यालय काव्य-प्रतियोगिताओं और क्षेत्रीय साहित्यिक सभाओं में सर्वोच्च सम्मान प्राप्त किए।',
    'about.milestone.3.title': '"स्वप्नों की अल्पना" का प्रकाशन',
    'about.milestone.3.desc':  'कंचन लता जी का यह चर्चित संकलन सांस्कृतिक विरासत की खोज के लिए राज्य-स्तरीय साहित्यिक सम्मानों से विभूषित हुआ।',
    'about.milestone.4.title': 'बेस्टसेलर संकलन एवं ग़ज़लें',
    'about.milestone.4.desc':  '"अंतर्मन की प्रतिध्वनि" और "दहलीज़ पर ग़ज़लें" ने भारत और विदेश के काव्य-प्रेमियों में व्यापक प्रशंसा पाई।',
    'about.milestone.5.title': 'अक्षर कैनवास की स्थापना',
    'about.milestone.5.desc':  'दो पीढ़ियों के दृष्टिकोण को "अक्षर कैनवास" के अंतर्गत एकजुट करना और आगामी भव्य संयुक्त संकलन की घोषणा।',

    // ── Poems Page ──
    'poems.subtitle':        'छंदों की काव्य-धारा',
    'poems.title1':          'कविता संकलन एवं',
    'poems.title2':          'प्रकाशित रचनाएँ',
    'poems.desc':            'कंचन लता जायसवाल और गरिमा सिंह की संपूर्ण प्रकाशित रचनाएँ, समकालीन ग़ज़लें और दार्शनिक कविताएँ यहाँ उपलब्ध हैं।',
    'poems.searchPlaceholder': 'शीर्षक, पंक्ति, पुस्तक या थीम से खोजें (जैसे मौन, भोर, प्रेम, एकांत)...',
    'poems.filter.all':      'सभी रचनाएँ',
    'poems.filter.kanchan':  'कंचन लता जायसवाल',
    'poems.filter.garima':   'गरिमा सिंह',
    'poems.filter.joint':    'सह-रचनाएँ',
    'poems.filter.allCats':  'सभी श्रेणियाँ एवं थीम',
    'poems.notFound':        'कोई कविता नहीं मिली',
    'poems.notFoundDesc':    'कृपया अलग खोज शब्द आज़माएँ या फ़िल्टर रीसेट करें।',
    'poems.resetFilters':    'फ़िल्टर रीसेट करें',
    'poems.readFull':        'पूरी कविता पढ़ें',
    'poems.publishedIn':     'प्रकाशित:',
    'poems.by':              'द्वारा',

    // ── Books Page ──
    'booksPage.subtitle':    'साहित्यिक विरासत',
    'booksPage.title1':      'प्रकाशित रचनाएँ एवं',
    'booksPage.title2':      'आगामी प्रकाशन',
    'booksPage.desc':        'कंचन लता जायसवाल और गरिमा सिंह के प्रकाशित कविता संग्रह, ग़ज़ल संकलन और प्रतीक्षित साहित्यिक कृतियाँ।',
    'booksPage.published':   'प्रकाशित कविता संग्रह',
    'booksPage.titlesAvail': 'शीर्षक उपलब्ध',
    'booksPage.upcoming':    'आगामी प्रकाशन',
    'booksPage.advanceAnn':  'अग्रिम घोषणा',
    'booksPage.author':      'रचयिता:',
    'booksPage.authors':     'रचयिताएँ:',
    'booksPage.publisher':   'प्रकाशक:',
    'booksPage.expected':    '✨ अपेक्षित:',
    'booksPage.readExcerpt': 'अंश पढ़ें',
    'booksPage.previewExcerpt': 'अंश देखें',
    'booksPage.orderAmazon': 'Amazon पर ऑर्डर करें',
    'booksPage.preorder':    'पूर्व-ऑर्डर पूछताछ',
    'booksPage.vip.title':   'हस्ताक्षरित संग्राहक संस्करण',
    'booksPage.vip.desc':    'क्या आप कंचन लता जायसवाल और गरिमा सिंह के व्यक्तिगत संदेश के साथ हस्ताक्षरित प्रतियाँ प्राप्त करना चाहते हैं? आज ही अग्रिम पूछताछ करें।',
    'booksPage.vip.btn':     'हस्ताक्षरित प्रति का अनुरोध करें',
    'booksPage.publishedYear': 'प्रकाशित',

    // ── Quotes Page ──
    'quotesPage.subtitle':   'साहित्यिक प्रेरणाएँ एवं विचार',
    'quotesPage.title1':     'महान रचयिताओं के',
    'quotesPage.title2':     'प्रिय उद्धरण',
    'quotesPage.desc':       'मिर्ज़ा ग़ालिब, महादेवी वर्मा, हरिवंश राय बच्चन, रूमी, गुलज़ार, टैगोर, अमृता प्रीतम जैसे महान रचयिताओं की वे कालातीत पंक्तियाँ जिन्होंने कंचन लता जायसवाल और गरिमा सिंह को गहराई से प्रेरित किया।',
    'quotesPage.readingNook': '📖 <strong>कवयित्रियों का पठन कक्ष:</strong> जब भी दोनों कवयित्रियाँ अन्य महान रचयिताओं की प्रसिद्ध पुस्तकें पढ़ती हैं और कोई छंद उनकी आत्मा को स्पर्श करता है, तो वे उसे अपने विचारों और अंतर्दृष्टि के साथ यहाँ सहेज लेती हैं।',
    'quotesPage.filter.all': 'सभी संकलित उद्धरण',
    'quotesPage.filter.kanchan': 'कंचन लता के चयन',
    'quotesPage.filter.garima':  'गरिमा सिंह के चयन',
    'quotesPage.source':     'स्रोत ग्रंथ:',
    'quotesPage.curatedBy':  '💡 संकलन:',
    'quotesPage.copied':     'कॉपी हो गया!',
    'quotesPage.copy':       'कॉपी करें',
    'quotesPage.artCard':    'कला कार्ड',
    'quotesPage.likes':      'पसंद',

    // ── Contact Page ──
    'contact.subtitle':      'संवाद एवं पूछताछ',
    'contact.title1':        'साहित्यिक आमंत्रण एवं',
    'contact.title2':        'पाठक पत्राचार',
    'contact.desc':          'काव्य उत्सवों, विश्वविद्यालय संगोष्ठियों, मीडिया साक्षात्कारों के लिए संपर्क करें या कवयित्रियों को व्यक्तिगत पत्र भेजें।',
    'contact.info.title':    'अक्षर कैनवास सचिवालय',
    'contact.info.desc':     'कवयित्री कंचन लता जायसवाल और गरिमा सिंह का आधिकारिक प्रबंधन एवं साहित्यिक बुकिंग कार्यालय।',
    'contact.info.email.lbl': 'ईमेल पत्राचार',
    'contact.info.phone.lbl': 'समन्वय डेस्क',
    'contact.info.loc.lbl':   'प्रमुख स्थान',
    'contact.form.heading':   'आमंत्रण या संदेश भेजें',
    'contact.form.sub':       'कृपया अपना विवरण नीचे प्रदान करें। हम सभी जानकारी को पूर्ण गोपनीयता के साथ संभालते हैं।',
    'contact.form.name':      'आपका नाम / संस्था *',
    'contact.form.namePh':    'जैसे: डॉ. राम प्रसाद / साहित्य अकादमी',
    'contact.form.email':     'ईमेल पता *',
    'contact.form.phone':     'संपर्क फ़ोन नंबर *',
    'contact.form.city':      'शहर एवं देश',
    'contact.form.cityPh':    'जैसे: नई दिल्ली, भारत',
    'contact.form.eventType': 'उद्देश्य / कार्यक्रम प्रकार *',
    'contact.form.date':      'अपेक्षित कार्यक्रम तिथि',
    'contact.form.message':   'आपका संदेश / कार्यक्रम विवरण *',
    'contact.form.messagePh': 'कृपया कार्यक्रम का विवरण, अपेक्षित काव्य-पाठ अवधि, या अपना व्यक्तिगत पत्र साझा करें...',
    'contact.form.submit':    'आमंत्रण / पत्र भेजें',
    'contact.event.1':        'राष्ट्रीय कवि सम्मेलन / मुशायरा',
    'contact.event.2':        'साहित्य उत्सव / मुख्य वक्ता',
    'contact.event.3':        'पुस्तक लोकार्पण एवं एकल काव्य-पाठ',
    'contact.event.4':        'लेखक-हस्ताक्षरित पुस्तक अनुरोध',
    'contact.event.5':        'कवयित्रियों को पाठक-पत्र',
    'contact.event.6':        'प्रेस एवं मीडिया साक्षात्कार',
    'contact.success.title':  'आपका संदेश प्राप्त हो गया!',
    'contact.success.desc':   'अक्षर कैनवास से संपर्क करने के लिए धन्यवाद। हमारी टीम आपकी पूछताछ की समीक्षा करके शीघ्र ही आपसे संपर्क करेगी।',
    'contact.success.btn':    'एक और संदेश भेजें',
    'contact.faq.subtitle':   'अक्सर पूछे जाने वाले प्रश्न',
    'contact.faq.title1':     'सामान्य',
    'contact.faq.title2':     'प्रश्न (FAQ)',
    'contact.faq.desc':       'कार्यक्रम आयोजन, बुकिंग समय-सीमा और साहित्यिक पत्राचार से संबंधित विवरण।',
    'contact.faq.q1': 'आयोजक कवयित्रियों को किसी कार्यक्रम या उत्सव के लिए कैसे आमंत्रित कर सकते हैं?',
    'contact.faq.a1': 'आप अनुमानित तिथियों, स्थान और दर्शकों के विवरण के साथ ऊपर दिए गए बुकिंग फ़ॉर्म का उपयोग करके अपनी पूछताछ सबमिट कर सकते हैं। हमारी साहित्यिक समन्वय समिति आमतौर पर 24 से 48 घंटों के भीतर उत्तर देती है।',
    'contact.faq.q2': 'क्या कंचन लता जायसवाल और गरिमा सिंह व्यक्तिगत रूप से पाठकों के पत्र पढ़ती हैं?',
    'contact.faq.a2': 'हाँ, हार्दिक पत्राचार, प्रतिक्रिया और पाठकों के विचार दोनों लेखिकाओं को बहुत प्रिय हैं। पाठक लेटरबॉक्स के माध्यम से भेजे गए सभी संदेश सीधे उन तक पहुँचते हैं।',
    'contact.faq.q3': 'क्या शैक्षणिक कार्यशालाएँ और विश्वविद्यालय पैनल सत्र उपलब्ध हैं?',
    'contact.faq.a3': 'हाँ, दोनों कवयित्रियाँ विश्वविद्यालयों, महाविद्यालयों और साहित्यिक संस्थाओं में रचनात्मक लेखन, काव्यशास्त्र और सांस्कृतिक विमर्श पर मास्टरक्लास देती हैं।',
    'contact.faq.q4': 'लेखक द्वारा हस्ताक्षरित प्रतियाँ अनुरोध करने की प्रक्रिया क्या है?',
    'contact.faq.a4': 'फ़ॉर्म में "हस्ताक्षरित प्रति अनुरोध" चुनें या अपने संदेश में उल्लेख करें। व्यक्तिगत शिलालेख के साथ विशेष प्रतियाँ तैयार की जाती हैं और आपके निर्दिष्ट पते पर भेजी जाती हैं।',
  },

  en: {
    // ── Navbar ──
    'nav.home':        'Home',
    'nav.about':       'About',
    'nav.poems':       'Poems',
    'nav.books':       'Books',
    'nav.quotes':      'Quotes',
    'nav.submitPoem':   'Submit Poem',
    'nav.contact':     'Contact',
    'nav.invitePoets': 'Invite Poets',
    'nav.poets':       'Kanchan Lata Jaiswal & Garima Singh',
    'lang.toggle':     'हिंदी',
    'lang.current':    'EN',

    // ── Hero ──
    'hero.badge':        'Akshar Canvas • Words • Art • Soul',
    'hero.title1':       'Where Thoughts Become Colors,',
    'hero.title2':       'And Words Shape into Literature.',
    'hero.subtitle':     'Poetesses Kanchan Lata Jaiswal & Garima Singh',
    'hero.lead':         'An evocative literary tapestry weaving traditional Indian emotional depth, contemporary romance, and philosophical introspection. Welcome to the golden bridge where two generations of poetic brilliance converge.',
    'hero.explorePoems': 'Explore Poetry Collection',
    'hero.discoverBooks':'Discover Published Books',
    'hero.badge1.role':  'Philosophy & Heritage',
    'hero.badge2.role':  'Modern Ghazals & Youth Voice',
    'hero.art.pill':     'AKSHAR CANVAS • WORDS • ART • SOUL',
    'hero.art.quote':    '"Upon the canvas of paper, when drops of ink descend, even silence blossoms into an eternal melody."',

    // ── Featured Poems ──
    'featuredPoems.subtitle': 'Poetic Currents',
    'featuredPoems.title1':   'Celebrated',
    'featuredPoems.title2':   'Poems & Ghazals',
    'featuredPoems.desc':     'A curated selection of acclaimed compositions capturing existential truths, tender romance, and cultural resonance.',
    'featuredPoems.readBtn':  'Read Full Poem',
    'featuredPoems.viewAll':  'View Full Poetry Collection',
    'featuredPoems.by':       'By',

    // ── Poets Spotlight ──
    'spotlight.subtitle':    'Literary Pillars',
    'spotlight.title1':      'Meet the',
    'spotlight.title2':      'Poets',
    'spotlight.desc':        'A harmonious synthesis of two distinct generations—bringing timeless cultural depth and vibrant modern sensibility to the forefront of poetry.',
    'spotlight.books':       'Books',
    'spotlight.service':     'Literary Service',
    'spotlight.journey':     'Creative Journey',
    'spotlight.readBio':     'Read Full Biography',

    // ── Books Showcase ──
    'books.subtitle':        'Literary Oeuvre',
    'books.title1':          'Published &',
    'books.title2':          'Upcoming Books',
    'books.desc':            'Explore the hardcover volumes and anticipated anthologies holding the immortal thoughts and verses of both authors.',
    'books.viewDetails':     'View Details & Excerpt',
    'books.viewAll':         'Discover All Books & Order Options',
    'books.upcoming':        '✨ Upcoming Release',
    'books.published':       'Published',

    // ── Quotes Carousel ──
    'quotes.subtitle':       'Literary Inspirations & Musings',
    'quotes.title1':         'Beloved Quotes from',
    'quotes.title2':         'Master Authors',
    'quotes.desc':           'Whenever Kanchan Lata and Garima read the timeless works of other legendary writers and a line touches their spirit, they preserve it here along with their reflections.',
    'quotes.viewAll':        'Explore All Quotes & Inspirations',
    'quotes.source':         'Source:',
    'quotes.curatedBy':      '💡 Curated by',
    'quotes.likes':          'Likes',
    'quotes.viewCard':       'View Card & Share',

    // ── Royal CTA ──
    'cta.tag':           'Literary Festivals & Poetry Recital Invitations',
    'cta.heading1':      'Elevate Your Gathering with',
    'cta.heading2':      'Immortal Verses & Resonance',
    'cta.sub':           'Invite poetesses Kanchan Lata Jaiswal and Garima Singh for National Kavi Sammelans, Mushairas, University Symposiums, Literature Festivals, and Book Reading recitals.',
    'cta.invite':        'Send Literary Invitation',
    'cta.write':         'Write Letter to Poets',

    // ── Footer ──
    'footer.brand.desc':     'The official literary sanctuary of acclaimed poets Kanchan Lata Jaiswal and Garima Singh. A timeless voyage where words, emotions, and cultural resonance weave together.',
    'footer.nav.heading':    'Navigation',
    'footer.nav.home':       'Home',
    'footer.nav.about':      'About the Poets',
    'footer.nav.poems':      'Poetry Collection',
    'footer.nav.books':      'Published Books',
    'footer.nav.quotes':     'Inspirations & Quotes',
    'footer.themes.heading': 'Themes & Works',
    'footer.theme.1':        'Life Philosophy & Mysticism',
    'footer.theme.2':        'Contemporary Love & Ghazals',
    'footer.theme.3':        'Feminine Voice & Empowerment',
    'footer.theme.4':        'Upcoming Grand Anthology',
    'footer.theme.5':        'Poetry Event Invitations',
    'footer.newsletter.heading': 'Poetry Gazette',
    'footer.newsletter.desc':    'Receive exclusive verses, manuscript excerpts, and event notifications directly to your inbox.',
    'footer.newsletter.placeholder': 'Enter your email address...',
    'footer.newsletter.btn':  'Subscribe',
    'footer.newsletter.success': '✨ Thank you! Your subscription is confirmed.',
    'footer.rights':          'All Rights Reserved.',
    'footer.authors':         'Authors:',

    // ── About ──
    'about.subtitle':        'Literary Pilgrimage',
    'about.title1':          'Biographies &',
    'about.title2':          'Poetic Philosophy',
    'about.desc':            'A profound convergence of two literary generations—where classical depth meets contemporary resonance.',
    'about.stat.volumes':    'Published Volumes:',
    'about.stat.verses':     'Composed Verses:',
    'about.stat.dedication': 'Literary Dedication:',
    'about.stat.ghazals':    'Composed Ghazals:',
    'about.stat.journey':    'Active Journey:',
    'about.honors':          'Major Recognitions & Honors',
    'about.timeline.subtitle': 'Footprints of Time',
    'about.timeline.title1': 'Milestones &',
    'about.timeline.title2': 'Key Achievements',
    'about.timeline.desc':   'Pivotal moments that shaped this lifelong dedication to the craft of poetry.',
    'about.milestone.1.title': 'The Genesis of a Literary Odyssey',
    'about.milestone.1.desc':  "Kanchan Lata Jaiswal's early classical verses received widespread recognition in leading national literary journals.",
    'about.milestone.2.title': "Garima Singh's Poetic Emergence",
    'about.milestone.2.desc':  'Young poetess Garima Singh achieved top honors across prestigious university poetry slams and regional literary gatherings.',
    'about.milestone.3.title': "Publication of 'Alpana of Dreams'",
    'about.milestone.3.desc':  "Kanchan Lata Ji's celebrated anthology was decorated with state-level literary honors for its exploration of cultural heritage.",
    'about.milestone.4.title': 'Bestselling Anthologies & Ghazals',
    'about.milestone.4.desc':  "'Echoes of the Inner Mind' and 'Ghazals on the Threshold' gained widespread acclaim among poetry lovers across India and abroad.",
    'about.milestone.5.title': 'Establishment of Akshar Canvas',
    'about.milestone.5.desc':  "Uniting the perspectives of two generations under 'Akshar Canvas' and announcing the forthcoming Grand Joint Anthology.",

    // ── Poems Page ──
    'poems.subtitle':        'Poetic River of Verses',
    'poems.title1':          'Poetry Anthology &',
    'poems.title2':          'Published Verses',
    'poems.desc':            'Explore the complete library of published verses, contemporary ghazals, and philosophical poems by Kanchan Lata Jaiswal and Garima Singh.',
    'poems.searchPlaceholder': 'Search by title, line, book, or theme (e.g. Silence, Dawn, Love, Solitude)...',
    'poems.filter.all':      'All Verses',
    'poems.filter.kanchan':  'Kanchan Lata Jaiswal',
    'poems.filter.garima':   'Garima Singh',
    'poems.filter.joint':    'Joint Compositions',
    'poems.filter.allCats':  'All Categories & Themes',
    'poems.notFound':        'No Poems Found',
    'poems.notFoundDesc':    'Please try a different search keyword or reset filters.',
    'poems.resetFilters':    'Reset Filters',
    'poems.readFull':        'Read Full Poem',
    'poems.publishedIn':     'Published in:',
    'poems.by':              'By',

    // ── Books Page ──
    'booksPage.subtitle':    'Literary Legacy',
    'booksPage.title1':      'Published Works &',
    'booksPage.title2':      'Upcoming Releases',
    'booksPage.desc':        'Discover the published poetry collections, ghazal anthologies, and anticipated literary works by Kanchan Lata Jaiswal and Garima Singh.',
    'booksPage.published':   'Published Poetry Collections',
    'booksPage.titlesAvail': 'Titles Available',
    'booksPage.upcoming':    'Upcoming Publications',
    'booksPage.advanceAnn':  'Advance Announcement',
    'booksPage.author':      'Author:',
    'booksPage.authors':     'Authors:',
    'booksPage.publisher':   'Publisher:',
    'booksPage.expected':    '✨ Expected:',
    'booksPage.readExcerpt': 'Read Excerpt',
    'booksPage.previewExcerpt': 'Preview Excerpt',
    'booksPage.orderAmazon': 'Order on Amazon',
    'booksPage.preorder':    'Pre-Order Inquiry',
    'booksPage.vip.title':   'Autographed Collector Editions',
    'booksPage.vip.desc':    'Would you like to receive personal signed copies inscribed with a bespoke message from poets Kanchan Lata Jaiswal and Garima Singh? Submit an advance inquiry today.',
    'booksPage.vip.btn':     'Request Author-Signed Copy',
    'booksPage.publishedYear': 'Published',

    // ── Quotes Page ──
    'quotesPage.subtitle':   'Literary Sanctuary & Inspirations',
    'quotesPage.title1':     'Beloved Quotes from',
    'quotesPage.title2':     'Master Authors',
    'quotesPage.desc':       'Timeless lines from classical and contemporary masters (Mirza Ghalib, Mahadevi Varma, Harivansh Rai Bachchan, Rumi, Gulzar, Tagore, Amrita Pritam) that have deeply inspired Kanchan Lata Jaiswal and Garima Singh.',
    'quotesPage.readingNook': '📖 <strong>The Poets\' Reading Nook:</strong> Whenever both poetesses read celebrated volumes from other masters and discover a verse that stirs the soul, they archive it here with their personal reflections and insights.',
    'quotesPage.filter.all': 'All Curated Quotes',
    'quotesPage.filter.kanchan': 'Kanchan Lata\'s Selections',
    'quotesPage.filter.garima':  'Garima Singh\'s Selections',
    'quotesPage.source':     'Source Volume:',
    'quotesPage.curatedBy':  '💡 Curated by',
    'quotesPage.copied':     'Copied!',
    'quotesPage.copy':       'Copy',
    'quotesPage.artCard':    'Art Card',
    'quotesPage.likes':      'Likes',

    // ── Contact Page ──
    'contact.subtitle':      'Dialogue & Inquiries',
    'contact.title1':        'Literary Invitations &',
    'contact.title2':        'Reader Correspondence',
    'contact.desc':          'Connect for poetry festivals, university symposiums, media interviews, or send personal letters directly to the poets.',
    'contact.info.title':    'Akshar Canvas Secretariat',
    'contact.info.desc':     'Official management and literary booking office for poetesses Kanchan Lata Jaiswal and Garima Singh.',
    'contact.info.email.lbl': 'Email Correspondence',
    'contact.info.phone.lbl': 'Coordination Desk',
    'contact.info.loc.lbl':   'Key Locations',
    'contact.form.heading':   'Send an Invitation or Message',
    'contact.form.sub':       'Please provide your details below. We treat all information with utmost confidentiality.',
    'contact.form.name':      'Your Name / Organization *',
    'contact.form.namePh':    'e.g. Dr. Arthur Miller / Sahitya Academy',
    'contact.form.email':     'Email Address *',
    'contact.form.phone':     'Contact Phone Number *',
    'contact.form.city':      'City & Country',
    'contact.form.cityPh':    'e.g. New Delhi, India',
    'contact.form.eventType': 'Purpose / Event Type *',
    'contact.form.date':      'Tentative Event Date',
    'contact.form.message':   'Your Message / Event Specifications *',
    'contact.form.messagePh': 'Please share event overview, preferred recital duration, or your personal letter...',
    'contact.form.submit':    'Send Invitation / Letter',
    'contact.event.1':        'National Kavi Sammelan / Mushaira',
    'contact.event.2':        'Literature Festival / Keynote Panel',
    'contact.event.3':        'Book Release & Solo Recital',
    'contact.event.4':        'Author-Signed Book Request',
    'contact.event.5':        'Reader Letter to Poets',
    'contact.event.6':        'Press & Media Interview',
    'contact.success.title':  'Your Message Has Been Received!',
    'contact.success.desc':   'Thank you for reaching out to Akshar Canvas. Our team will review your inquiry and get back to you shortly.',
    'contact.success.btn':    'Submit Another Message',
    'contact.faq.subtitle':   'Frequently Asked Questions',
    'contact.faq.title1':     'General',
    'contact.faq.title2':     'Queries (FAQ)',
    'contact.faq.desc':       'Details regarding event hosting, booking timelines, and literary correspondence.',
    'contact.faq.q1': 'How can organizers invite the poetesses for an event or festival?',
    'contact.faq.a1': 'You can submit your event inquiry using the booking form above with tentative dates, location, and audience profile. Our literary coordination committee typically responds within 24 to 48 hours.',
    'contact.faq.q2': 'Do Kanchan Lata Jaiswal and Garima Singh personally read reader letters?',
    'contact.faq.a2': 'Yes, heartfelt correspondence, feedback, and reader reflections are deeply cherished by both authors. All messages sent through the Reader Letterbox reach them directly.',
    'contact.faq.q3': 'Are academic workshops and university panel sessions available?',
    'contact.faq.a3': 'Yes, both poetesses frequently deliver masterclasses on creative writing, poetics, and cultural discourse at universities, colleges, and literary societies.',
    'contact.faq.q4': 'What is the process to request author-autographed copies?',
    'contact.faq.a4': 'Select \'Signed Copy Request\' in the form or mention it in your message. Custom inscribed copies are prepared and shipped to your designated postal address.',
  }
};

// ─── Provider ─────────────────────────────────────────────────────────────────
export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    try {
      return localStorage.getItem('akshar_lang') || 'hi';
    } catch {
      return 'hi';
    }
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    try { localStorage.setItem('akshar_lang', newLang); } catch {}
  };

  const toggleLang = () => setLang(lang === 'hi' ? 'en' : 'hi');

  const t = useCallback((key) => {
    return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
